### ISSUE TITLE
Particle\Validator\Validator not found

### ISSUE THREAD

**Issue by Nicolas-PL** [pmmp/RconServer#1]
Hello,

I have this error with plugin : 

Class 'Particle\Validator\Validator' not found"

PocketMine-MP version 3.6.2

Thanks

**Comment by dktapps** [comment]
it doesn't even run on 3.6.2... https://github.com/pmmp/RconServer/blob/03cb0962b255f21943a40ee8e25e3ec9594a9218/plugin.yml#L4

**Comment by Nicolas-PL** [comment]
So impossible to have rcon on version 3.6.2...

**Comment by dktapps** [comment]
Incorrect, in 3.6.2 it is built into the core.
