### ISSUE TITLE
Crashed while starting

### ISSUE THREAD

**Issue by Gaprix** [pmmp/RconServer#6]
[Thu_Jun_24-19.29.11-UTC_2021.log](https://github.com/pmmp/RconServer/files/6711705/Thu_Jun_24-19.29.11-UTC_2021.log)

**Comment by dktapps** [comment]
Don't use PHP 8.0. It's not supported yet.

**Comment by dktapps** [comment]
Clarification: This is caused by pthreads, not by the plugin itself. pthreads doesn't support socket sharing on 8.0 yet.
